-- MySQL Script generated by MySQL Workbench
-- Sun Jul 21 19:13:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema railway
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `railway` ;

-- -----------------------------------------------------
-- Schema railway
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `railway` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `railway` ;

-- -----------------------------------------------------
-- Table `railway`.`airline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`airline` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`country` (
  `id` VARCHAR(5) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `id` ON `railway`.`country` (`id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `railway`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `idcountry` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_city_country`
    FOREIGN KEY (`idcountry`)
    REFERENCES `railway`.`country` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `id` ON `railway`.`city` (`id` ASC) VISIBLE;

CREATE INDEX `fk_city_country` ON `railway`.`city` (`idcountry` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `railway`.`airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`airport` (
  `id` VARCHAR(5) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `idcity` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_airport_idcity`
    FOREIGN KEY (`idcity`)
    REFERENCES `railway`.`city` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_airport_idcity` ON `railway`.`airport` (`idcity` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `railway`.`documenttype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`documenttype` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`customer` (
  `id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `age` INT NOT NULL,
  `doc_type` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_customer_documenttype_id`
    FOREIGN KEY (`doc_type`)
    REFERENCES `railway`.`documenttype` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `id` ON `railway`.`customer` (`id` ASC) VISIBLE;

CREATE INDEX `fk_customer_documenttype_id` ON `railway`.`customer` (`doc_type` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `railway`.`tripulationrole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`tripulationrole` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`employee` (
  `id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  `idrole` INT NOT NULL,
  `entrydate` DATE NULL DEFAULT NULL,
  `idairline` INT NOT NULL,
  `idairport` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_employee_airline_id`
    FOREIGN KEY (`idairline`)
    REFERENCES `railway`.`airline` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_employee_idairport`
    FOREIGN KEY (`idairport`)
    REFERENCES `railway`.`airport` (`id`),
  CONSTRAINT `fk_employee_roles_id`
    FOREIGN KEY (`idrole`)
    REFERENCES `railway`.`tripulationrole` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `id` ON `railway`.`employee` (`id` ASC) VISIBLE;

CREATE INDEX `fk_employee_roles_id` ON `railway`.`employee` (`idrole` ASC) VISIBLE;

CREATE INDEX `fk_employee_airline_id` ON `railway`.`employee` (`idairline` ASC) VISIBLE;

CREATE INDEX `fk_employee_idairport` ON `railway`.`employee` (`idairport` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `railway`.`employe_airline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`employe_airline` (
  `id_employee` VARCHAR(10) NOT NULL,
  `id_airline` INT NOT NULL,
  PRIMARY KEY (`id_employee`, `id_airline`),
  CONSTRAINT `fk_employe_airline_airl_id`
    FOREIGN KEY (`id_airline`)
    REFERENCES `railway`.`airline` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_employe_airline_emp_id`
    FOREIGN KEY (`id_employee`)
    REFERENCES `railway`.`employee` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_employe_airline_airl_id` ON `railway`.`employe_airline` (`id_airline` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `railway`.`flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`flight` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `trip_date` DATE NOT NULL,
  `price_trip` DOUBLE(7,2) NULL DEFAULT NULL,
  `orig_city` INT NULL DEFAULT NULL,
  `dest_city` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_flight_dest_city`
    FOREIGN KEY (`dest_city`)
    REFERENCES `railway`.`city` (`id`),
  CONSTRAINT `fk_flight_orig_city`
    FOREIGN KEY (`orig_city`)
    REFERENCES `railway`.`city` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_flight_orig_city` ON `railway`.`flight` (`orig_city` ASC) VISIBLE;

CREATE INDEX `fk_flight_dest_city` ON `railway`.`flight` (`dest_city` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `railway`.`manufacturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`manufacturer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`model` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `idmanufacturer` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_model_manufacturer_id`
    FOREIGN KEY (`idmanufacturer`)
    REFERENCES `railway`.`manufacturer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_model_manufacturer_id` ON `railway`.`model` (`idmanufacturer` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `railway`.`planestatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`planestatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`plane`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`plane` (
  `id` VARCHAR(30) NOT NULL,
  `capacity` INT NOT NULL,
  `fabrication_date` DATE NOT NULL,
  `id_status` INT NOT NULL,
  `id_model` INT NOT NULL,
  `id_airline` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_plane_airline_id`
    FOREIGN KEY (`id_airline`)
    REFERENCES `railway`.`airline` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_plane_model_id`
    FOREIGN KEY (`id_model`)
    REFERENCES `railway`.`model` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_plane_status_id`
    FOREIGN KEY (`id_status`)
    REFERENCES `railway`.`planestatus` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `plates` ON `railway`.`plane` (`id` ASC) VISIBLE;

CREATE INDEX `fk_plane_status_id` ON `railway`.`plane` (`id_status` ASC) VISIBLE;

CREATE INDEX `fk_plane_model_id` ON `railway`.`plane` (`id_model` ASC) VISIBLE;

CREATE INDEX `fk_plane_airline_id` ON `railway`.`plane` (`id_airline` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `railway`.`flight_connection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`flight_connection` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `connection_number` VARCHAR(20) NOT NULL,
  `id_trip` INT NOT NULL,
  `id_plane` VARCHAR(30) NOT NULL,
  `dest_airport` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_flight_connection_plane_id`
    FOREIGN KEY (`id_plane`)
    REFERENCES `railway`.`plane` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_flight_connection_trip_id`
    FOREIGN KEY (`id_trip`)
    REFERENCES `railway`.`flight` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_flightconn_destairport`
    FOREIGN KEY (`dest_airport`)
    REFERENCES `railway`.`airport` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_flight_connection_trip_id` ON `railway`.`flight_connection` (`id_trip` ASC) VISIBLE;

CREATE INDEX `fk_flightconn_destairport` ON `railway`.`flight_connection` (`dest_airport` ASC) VISIBLE;

CREATE INDEX `fk_flight_connection_plane_id` ON `railway`.`flight_connection` (`id_plane` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `railway`.`flightfare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`flightfare` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NULL DEFAULT NULL,
  `value` DOUBLE(7,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`flightbooking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`flightbooking` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `idflight` INT NOT NULL,
  `idcustomer` VARCHAR(10) NOT NULL,
  `idfares` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_flightbooking_customer_id`
    FOREIGN KEY (`idcustomer`)
    REFERENCES `railway`.`customer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_flightbooking_fares_id`
    FOREIGN KEY (`idfares`)
    REFERENCES `railway`.`flightfare` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_flightbooking_flight_id`
    FOREIGN KEY (`idflight`)
    REFERENCES `railway`.`flight` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_flightbooking_flight_id` ON `railway`.`flightbooking` (`idflight` ASC) VISIBLE;

CREATE INDEX `fk_flightbooking_customer_id` ON `railway`.`flightbooking` (`idcustomer` ASC) VISIBLE;

CREATE INDEX `fk_flightbooking_fares_id` ON `railway`.`flightbooking` (`idfares` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `railway`.`gate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`gate` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gatenumber` VARCHAR(10) NOT NULL,
  `idairport` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_gate_idairport`
    FOREIGN KEY (`idairport`)
    REFERENCES `railway`.`airport` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_gate_idairport` ON `railway`.`gate` (`idairport` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `railway`.`revision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`revision` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `revision_date` DATE NOT NULL,
  `id_plane` VARCHAR(30) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `id_emp` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_revision_employee_id`
    FOREIGN KEY (`id_emp`)
    REFERENCES `railway`.`employee` (`id`),
  CONSTRAINT `fk_revision_plane_id`
    FOREIGN KEY (`id_plane`)
    REFERENCES `railway`.`plane` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_revision_plane_id` ON `railway`.`revision` (`id_plane` ASC) VISIBLE;

CREATE INDEX `fk_revision_employee_id` ON `railway`.`revision` (`id_emp` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `railway`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`tripcrew`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`tripcrew` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idemployee` VARCHAR(10) NOT NULL,
  `idconnection` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tripcrew_connection_id`
    FOREIGN KEY (`idconnection`)
    REFERENCES `railway`.`flight_connection` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tripcrew_employee_id`
    FOREIGN KEY (`idemployee`)
    REFERENCES `railway`.`employee` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_tripcrew_employee_id` ON `railway`.`tripcrew` (`idemployee` ASC) VISIBLE;

CREATE INDEX `fk_tripcrew_connection_id` ON `railway`.`tripcrew` (`idconnection` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `railway`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `idrole` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`idrole`)
    REFERENCES `railway`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `username` ON `railway`.`user` (`username` ASC) VISIBLE;

CREATE UNIQUE INDEX `email` ON `railway`.`user` (`email` ASC) VISIBLE;

CREATE INDEX `fk_user_role` ON `railway`.`user` (`idrole` ASC) VISIBLE;

USE `railway` ;

-- -----------------------------------------------------
-- procedure CreateAirports
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `CreateAirports`(
    IN id VARCHAR(5),
    IN name VARCHAR(50),
    IN idcity INT
)
BEGIN
    INSERT INTO airport (id, name, idcity) VALUES 
    (id, name, idcity);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DeleteByIdInt
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `DeleteByIdInt`(
    IN table_name VARCHAR(64),
    IN object_id INT
)
BEGIN
    SET @query = CONCAT('DELETE FROM ', table_name, ' WHERE id = ''', object_id, '''');
    
    PREPARE stmt FROM @query;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DeleteByIdVarchar
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `DeleteByIdVarchar`(
    IN table_name VARCHAR(64),
    IN object_id VARCHAR(30)
)
BEGIN
    SET @query = CONCAT('DELETE FROM ', table_name, ' WHERE id = ''', object_id, '''');
    
    PREPARE stmt FROM @query;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure EditColumnWithDynamicDataType
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `EditColumnWithDynamicDataType`(
    IN p_table_name VARCHAR(64),
    IN p_column_name VARCHAR(64),
    IN p_new_value VARCHAR(255),
    IN p_new_value_type VARCHAR(20), -- Nuevo parámetro para el tipo de dato del nuevo valor
    IN p_data_type VARCHAR(20),
    IN p_object_id VARCHAR(30)
)
BEGIN
    DECLARE sql_query VARCHAR(1000);
    DECLARE query_suffix VARCHAR(100);

    SET @table_name = p_table_name;
    SET @column_name = p_column_name;
    SET @new_value = p_new_value;
    SET @new_value_type = p_new_value_type; -- Nuevo parámetro para el tipo de dato del nuevo valor
    SET @object_id = p_object_id;

    -- Construir la parte inicial de la sentencia SQL
    SET @query = CONCAT('UPDATE ', @table_name, ' SET ', @column_name, ' = ');

    -- Determinar cómo agregar el nuevo valor basado en su tipo de dato
    IF p_new_value_type = 'INT' THEN
        SET @query = CONCAT(@query, 'CAST(? AS SIGNED)');
    ELSEIF p_new_value_type = 'DATE' THEN
        SET @query = CONCAT(@query, 'STR_TO_DATE(?, ''%Y-%m-%d'')');
    ELSE
        SET @query = CONCAT(@query, '?');
    END IF;

    -- Agregar la parte final de la sentencia SQL
    SET @query = CONCAT(@query, ' WHERE id = ?');

    -- Preparar y ejecutar la sentencia SQL
    PREPARE stmt FROM @query;
    IF p_new_value_type = 'DATE' THEN
        SET @query_suffix = DATE_FORMAT(@new_value, '%Y-%m-%d');
    ELSE
        SET @query_suffix = @new_value;
    END IF;
    
    EXECUTE stmt USING @query_suffix, @object_id;
    DEALLOCATE PREPARE stmt;

    SELECT 1; -- Opcional: devolver algo si es necesario
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure EditColumnidVarAndInt
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `EditColumnidVarAndInt`(
    IN p_table_name VARCHAR(64),
    IN p_column_name VARCHAR(64),
    IN p_new_value VARCHAR(255),
    IN p_data_type VARCHAR(20),
    IN p_object_id VARCHAR(30)
)
BEGIN
    DECLARE sql_query VARCHAR(1000);

    SET @table_name = p_table_name;
    SET @column_name = p_column_name;
    SET @new_value = p_new_value;
    SET @object_id = p_object_id;
    
    SET @query = CONCAT('UPDATE ', @table_name, ' SET ', @column_name, ' = ');
    
    IF p_data_type = 'INT' THEN
        SET @query = CONCAT(@query, 'CAST(? AS SIGNED)');
    ELSE
        SET @query = CONCAT(@query, '?');
    END IF;
    
    SET @query = CONCAT(@query, ' WHERE id = ?');
    
    PREPARE stmt FROM @query;
    EXECUTE stmt USING @new_value, @object_id;
    DEALLOCATE PREPARE stmt;
    
    SELECT 1;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure EditIntColumnidInt
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `EditIntColumnidInt`(
    IN p_table_name VARCHAR(64),
    IN p_column_name VARCHAR(64),
    IN p_new_value INT,
    IN p_object_id INT
)
BEGIN
    DECLARE sql_query VARCHAR(1000);
    
    SET @table_name = p_table_name;
    SET @column_name = p_column_name;
    SET @new_value = p_new_value;
    SET @object_id = p_object_id;
    
    SET @query = CONCAT('UPDATE ', @table_name, ' SET ', @column_name, ' = ? WHERE id = ?');
    
    PREPARE stmt FROM @query;
    
    EXECUTE stmt USING @new_value, @object_id;
    DEALLOCATE PREPARE stmt;
    SELECT 1;
    
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure EditIntColumnidVar
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `EditIntColumnidVar`(
    IN p_table_name VARCHAR(64),
    IN p_column_name VARCHAR(64),
    IN p_new_value INT,
    IN p_object_id VARCHAR(10)
)
BEGIN
    DECLARE sql_query VARCHAR(1000);
    
    SET @table_name = p_table_name;
    SET @column_name = p_column_name;
    SET @new_value = p_new_value;
    SET @object_id = p_object_id;
    
    SET @query = CONCAT('UPDATE ', @table_name, ' SET ', @column_name, ' = ? WHERE id = ?');
    
    PREPARE stmt FROM @query;
    
    EXECUTE stmt USING @new_value, @object_id;
    DEALLOCATE PREPARE stmt;
    SELECT 1;
    
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure EditVarcharColumnIdVar
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `EditVarcharColumnIdVar`(
    IN p_table_name VARCHAR(64),
    IN p_column_name VARCHAR(64),
    IN p_new_value VARCHAR(64),
    IN p_object_id VARCHAR(10)
)
BEGIN
    DECLARE sql_query VARCHAR(1000);
    
    SET @table_name = p_table_name;
    SET @column_name = p_column_name;
    SET @new_value = p_new_value;
    SET @object_id = p_object_id;
    
    SET @query = CONCAT('UPDATE ', @table_name, ' SET ', @column_name, ' = ? WHERE id = ?');
    
    PREPARE stmt FROM @query;
    
    EXECUTE stmt USING @new_value, @object_id;
    DEALLOCATE PREPARE stmt;
    SELECT 1;
    
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure EditVarcharColumnidInt
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `EditVarcharColumnidInt`(
    IN p_table_name VARCHAR(64),
    IN p_column_name VARCHAR(64),
    IN p_new_value VARCHAR(64),
    IN p_object_id INT
)
BEGIN
    DECLARE sql_query VARCHAR(1000);
    
    SET @table_name = p_table_name;
    SET @column_name = p_column_name;
    SET @new_value = p_new_value;
    SET @object_id = p_object_id;
    
    SET @query = CONCAT('UPDATE ', @table_name, ' SET ', @column_name, ' = ? WHERE id = ?');
    
    PREPARE stmt FROM @query;
    
    EXECUTE stmt USING @new_value, @object_id;
    DEALLOCATE PREPARE stmt;
    SELECT 1;
    
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure createDocType
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `createDocType`(
    IN name_insert VARCHAR(40)
)
BEGIN
    INSERT INTO documenttype (name) 
    VALUES (name_insert);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure createRevision
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `createRevision`(
    IN date_insert VARCHAR(40),
    IN id_plane_insert VARCHAR(30),
    IN desc_insert TEXT,
    IN id_emp_insert VARCHAR(10)
)
BEGIN
    INSERT INTO revision (revision_date, id_plane, description, id_emp) 
    VALUES (date_insert, id_plane_insert, desc_insert, id_emp_insert);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure flightFareRegister
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `flightFareRegister`(
    IN flightFare_name VARCHAR(30),
    IN flightFare_value DOUBLE(7,2)
)
BEGIN
    INSERT INTO flightfare (id, name, value) 
    VALUES (NULL, flightFare_name, flightFare_value);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure planeRegister
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `planeRegister`(
    IN id_insert VARCHAR(30),
    IN capacity_insert INT,
    IN fabrication_date_insert DATE,
    IN id_status_insert INT,
    IN id_model_insert INT,
    IN id_airline_insert INT
)
BEGIN
    INSERT INTO plane (id, capacity, fabrication_date, id_status, id_model, id_airline) 
    VALUES (id_insert, capacity_insert, fabrication_date_insert, id_status_insert, id_model_insert, id_airline_insert);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure showAllAirports
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `showAllAirports`()
BEGIN
    SELECT a.id,
           a.name,
           c.name as city_name
    FROM airport a
    JOIN city c ON a.idcity = c.id;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure showAllPlanes
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `showAllPlanes`()
BEGIN
    SELECT
        p.id,
        p.capacity,
        p.fabrication_date,
        pst.name AS status_name,
        m.name AS model_name,
        air.name AS airline_name
    FROM plane AS p
    JOIN planestatus AS pst ON pst.id = p.id_status
    JOIN model AS m ON m.id = p.id_model
    JOIN airline AS air ON air.id = p.id_airline;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure showAllRegs
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `showAllRegs`(
    IN table_name VARCHAR(64)
)
BEGIN
    SET @query = CONCAT('SELECT * FROM ', table_name);
    PREPARE stmt FROM @query;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure showFlightById
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `showFlightById`(
    IN object_id INT
)
BEGIN
    SET @query = CONCAT('
		SELECT
			f.id,
			f.trip_date,
            f.price_trip,
            c1.name AS orig_city,
            c2.name AS dest_city
		FROM flight AS f
		JOIN city AS c1 ON c1.id = f.orig_city
        JOIN city AS c2 ON c2.id = f.dest_city
        WHERE f.id = ''', object_id, ''''
    );
    
    PREPARE stmt FROM @query;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure showFlights
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `showFlights`()
BEGIN
    SET @query = CONCAT('
		SELECT
			f.id,
			f.trip_date,
            f.price_trip,
            c1.name AS orig_city,
            c2.name AS dest_city
		FROM flight AS f
		JOIN city AS c1 ON c1.id = f.orig_city
        JOIN city AS c2 ON c2.id = f.dest_city;
    ');
    
    PREPARE stmt FROM @query;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure showInformationTable
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `showInformationTable`(
    IN table_name VARCHAR(30)
)
BEGIN
    SET @query = CONCAT('SELECT * FROM ', table_name);
    PREPARE stmt FROM @query;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure showObjectInformation
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `showObjectInformation`(
    IN table_name VARCHAR(64),
    IN object_id INT
)
BEGIN
    SET @query = CONCAT('SELECT * FROM ', table_name, ' WHERE id = ', object_id);
    
    PREPARE stmt FROM @query;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure showObjectInformationIDVARCHAR
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `showObjectInformationIDVARCHAR`(
    IN table_name VARCHAR(64),
    IN object_id VARCHAR(3)
)
BEGIN
    SET @query = CONCAT('SELECT * FROM ', table_name, ' WHERE id = ''', object_id, '''');
    
    PREPARE stmt FROM @query;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure showObjectInformationIDVARCHARPlane
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `showObjectInformationIDVARCHARPlane`(
    IN object_id VARCHAR(30)
)
BEGIN
    SET @query = CONCAT('
		SELECT
			p.id,
			p.capacity,
			p.fabrication_date,
			pst.name AS status_name,
			m.name AS model_name,
			air.name AS airline_name
		FROM plane AS p
		JOIN planestatus AS pst ON pst.id = p.id_status
		JOIN model AS m ON m.id = p.id_model
		JOIN airline AS air ON air.id = p.id_airline
        WHERE p.id = ''', object_id, ''''
    );
    
    PREPARE stmt FROM @query;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure showObjectInformationVarchar
-- -----------------------------------------------------

DELIMITER $$
USE `railway`$$
CREATE DEFINER=`root`@`%` PROCEDURE `showObjectInformationVarchar`(
    IN table_name VARCHAR(64),
    IN column_name VARCHAR(64),
    IN object_identifier VARCHAR(64)
)
BEGIN
    SET @query = CONCAT('SELECT * FROM ', table_name, ' WHERE ', column_name, ' = \'', object_identifier, '\'');

    PREPARE stmt FROM @query;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CALL showObjectInformationVarchar("flightbooking", "idcustomer", "1097489826");